### PR TITLE
Repo File Sync: .sync/rust_config/rustfmt.toml: Use Rust default of 4 space indentation

### PR DESCRIPTION
**Pull request by uefibot**
## Description

Format only.  `rustfmt.toml` now defaults to tab_spaces to 4 (earlier 2).
No functional changes.

- [ ] Impacts functionality?
- [ ] Impacts security?
- [ ] Breaking change?
- [ ] Includes tests?
- [ ] Includes documentation?

## How This Was Tested

No functional change.

## Integration Instructions

N/A

---

synced local file(s) with [microsoft/mu_devops](https://github.com/microsoft/mu_devops).

🤖: View the [Repo File Sync Configuration File](https://github.com/microsoft/mu_devops/blob/main/.sync/Files.yml) to see how files are synced.

---

This PR was created automatically by the [repo-file-sync-action](https://github.com/BetaHuhn/repo-file-sync-action) workflow run [#10037882152](https://github.com/microsoft/mu_devops/actions/runs/10037882152)

### CODE REVIEW

**Comment by vineelko** [comment]
@joschock, Not sure why I am unable to include you as the reviewer(your name do not show up). I think the files in this PR are related to HID package. So appreciate if you could take a look at the PR. It changes the indentation from 2 to 4 spaces.

**Comment by vineelko** [comment]
@joschock, Not sure why I am unable to include you as the reviewer(your name do not show up). I think the files in this PR are related HID package. So appreciate if you could take a look at the PR.

**Review by joschock — APPROVED** [review]

**Review by makubacki — APPROVED** [review]

**Comment by makubacki** [comment]
> @joschock, Not sure why I am unable to include you as the reviewer(your name do not show up). I think the files in this PR are related HID package. So appreciate if you could take a look at the PR.

John is not a part of the Mu team so he does not have write permission to this repo. We still use his review as criteria for completion of the PR.

**Comment by makubacki** [comment]
Please make sure to use "Squash" on this PR so the bot commit with the old text is not directly merged and a single commit using the PR description is merged.

**Comment by vineelko** [comment]
> Please make sure to use "Squash" on this PR so the bot commit with the old text is not directly merged and a single commit using the PR description is merged.

Sure Machael. Thanks for the headsup.

**Review by apop5 — APPROVED** [review]

**Pull request merged**
