### PR TITLE
DfciPkg/UnitTests/pip-requirements.txt: Remove pytool-library; bump robot framework

### PR DESCRIPTION
**Pull request by makubacki**
## Description

- Removes edk2-pytool-library since it has a very old version and
   the module can be picked up from (1) the main repo
   pip-requirements.txt or (2) the edk2-pytool-extensions dependency.

- Updates robotframework pip module version since it also now very old.

- [ ] Breaking change?
  - Will this change break pre-existing builds or functionality without action being taken?
  **No** - Should not be breaking for the reasons mentioned in the description.

## How This Was Tested

Todo

## Integration Instructions

N/A

Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>

### CODE REVIEW

**Comment by makubacki** [comment]
@spbrogan - I only found this section in the documentation that is related to this change - [DfciPkg/UnitTests/DfciTests - Setting up the HOST system](https://github.com/microsoft/mu_plus/tree/release/202208/DfciPkg/UnitTests/DfciTests#setting-up-the-host-system).

It only references that the `pip-requirements.txt` file should be installed but does not mention the contents. It does reference Python 3.9.4 but updating that is a bit unrelated to this change and probably fine to leave.

**Comment by makubacki** [comment]
@mikeytdisco, this is something I found when going through the pip modules pulled down in our pipelines.

I don't have an environment set up to run the tests. Have you been running them recently? Could you try including this change the next time you run the robot tests?

**Review by apop5 — APPROVED** [review]

**Comment by makubacki** [comment]
Comment to bump as a reminder

**Comment by makubacki** [comment]
Moved to issue in mu_feature_dfci - https://github.com/microsoft/mu_feature_dfci/issues/46

**Pull request closed without merging**
