### PR TITLE
Fix build warnings in 201808 release builds

### PR DESCRIPTION
**Pull request by neilsh-msft**
- add missing initializer braces
- remove unused code in MsPlatform.c

### CODE REVIEW

**Comment by corthon** [comment]
Waiting to hear back from Mike about the removed function.

**Comment by spbrogan** [comment]
Can you please resolve conflict in BdsPlatform.h by taking the release version.  Other change is good.

**Comment by neilsh-msft** [comment]
Updated BdsPlatform.h

**Comment by neilsh-msft** [comment]
Ping?

**Review by mikeytdisco — APPROVED** [review]

**Review by spbrogan — APPROVED** [review]

**Pull request merged**
