### PR TITLE
Changing the status returned by RequestToLock in Foundation.

### PR DESCRIPTION
**Pull request by corthon**
VariablePolicy Disabled is considered a valid condition, but the RequestToLock interface to VariablePolicy would return an error if Disabled. This wouldn't be a problem normally, but many places will ASSERT if RequestToLock returns an error.

This may be re-evaluated in the future, but it should also encourage drivers to move away from VariableLockProtocol and towards VariablePolicyProtocol.

### CODE REVIEW

**Review by dmitryantipov — APPROVED** [review]

**Review by kuqin12 — APPROVED** [review]

**Comment by corthon** [comment]
@dmitryantipov and @kuqin12...
Still look good? I made some changes after you saw it.

**Comment by kuqin12** [comment]
> @dmitryantipov and @kuqin12...
> Still look good? I made some changes after you saw it.

Looks even better ~

**Comment by corthon** [comment]
@spbrogan, this one good, too?

**Comment by spbrogan** [comment]
Yes.  Looks good
________________________________

**Pull request merged**
