### PR TITLE
Update reset notification list to be notified before NVMe

### PR DESCRIPTION
**Pull request by mikeytdisco**
## Description

Reset notification was handled by the NVMe driver before the AdvLogger could write the log to disk.

- [No] Breaking change?
  - Will this change break pre-existing builds or functionality without action being taken?

## How This Was Tested

Tested on multiple systems.

## Integration Instructions

N/A

### CODE REVIEW

**Comment by makubacki** [comment]
Is/was there a change to the NVMe code? If so, could you link that in the description for reference?

**Comment by mikeytdisco** [comment]
There was no change to the NVMe code.  The Reset System driver processes 3 queues.  Both NVMe and AdvLogger were using the second queue processed by ResetSystemRuntimeDxe. AdvLogger was changed to use the first queue processed by ResetSystemRuntimeDxe.

**Comment by spbrogan** [comment]
Not sure about this change.  You are leveraging the "filter" list.
When we developed the new reset code we wrote some documentation about how it should be used.  Do you know where that is?  I don't see it in edk2.

**Review by spbrogan — CHANGES_REQUESTED** [review]
I would like to see the docs and confirm this is acceptable use

**Review by apop5 — APPROVED** [review]

**Review by spbrogan — APPROVED** [review]
this looks like it should work and is aligned with the requirements of the api headers.

**Pull request merged**
